
server:
  port: 3395

 
  
      
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:test
    username: isha
    jpa:
     spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    
  mvc:
    view:
     prefix: /views/
     suffix: .jsp
 
app1:
  messages:
    saveSuccess: Contact save Sucessfully
    saveFail: Constant Failed To Save 
